/**
 * Seed Data
 * 
 * Contains all the seed data for properties, events, and users.
 * Separated from seed.ts for better organization and maintainability.
 */

import { EventStatus, PaymentType } from '@prisma/client';

/**
 * Superadmin user configuration
 */
export const superAdminConfig = {
  email: process.env.ADMIN_EMAIL || 'admin@podocarpus.local',
  password: process.env.ADMIN_PASSWORD || 'admin123',
  firstName: 'System',
  lastName: 'Administrator',
};

/**
 * Properties seed data
 * Source: Assets 15.12.2025.csv — 29 properties
 *
 * Fields mapped from CSV → Property model:
 *   buildingName, unitNo, floor, condition (furnishing status),
 *   unitTotalSize (title deed sqft), serviceChargePerSqft, serviceChargeTotal,
 *   contractValue (purchased price), netRoiMin/Max (net ROI per annum),
 *   area/city derived from location column, isVacant from rent status.
 */
export const properties = [
  // ── 1 ── Dubai Marina / Marina Pinnacle ──────────────────────────────────
  {
    title: 'Marina Pinnacle - Unit 5105',
    description: 'Furnished apartment with balcony in Marina Pinnacle, Dubai Marina.',
    area: 'Dubai Marina',
    buildingName: 'Marina Pinnacle',
    contractValue: 1850000,
    unitNo: '5105',
    floor: 51,
    condition: 'Furnished & balcony',
    unitTotalSize: 1583.26,
    apartmentSize: 1583.26,
    serviceChargePerSqft: 17.28,
    serviceChargeTotal: 24760.34,
    status: 'Vacant',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/marina-pinnacle-5105.avif'],
    assets: [],
    netRoiMin: null,
    netRoiMax: null,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: true,
  },
  // ── 2 ── Dubai Marina / Marina Pinnacle ──────────────────────────────────
  {
    title: 'Marina Pinnacle - Unit 5904',
    description: 'Unfurnished apartment with balcony in Marina Pinnacle, Dubai Marina.',
    area: 'Dubai Marina',
    buildingName: 'Marina Pinnacle',
    contractValue: 1940000,
    unitNo: '5904',
    floor: 59,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 1583.26,
    apartmentSize: 1583.26,
    serviceChargePerSqft: 17.28,
    serviceChargeTotal: 24760.34,
    status: 'Vacant',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/marina-pinnacle-5904.avif'],
    assets: [],
    netRoiMin: null,
    netRoiMax: null,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: true,
  },
  // ── 3 ── Al Furjan / Prime Residency 3 ───────────────────────────────────
  {
    title: 'Prime Residency 3 - Unit 320',
    description: 'Fully fitted kitchen with balcony in Prime Residency 3, Al Furjan.',
    area: 'Al Furjan',
    buildingName: 'Prime Residency 3',
    contractValue: 456569,
    unitNo: '320',
    floor: 3,
    condition: 'Fully fitted kitchen & balcony',
    unitTotalSize: 401.49,
    apartmentSize: 401.49,
    serviceChargePerSqft: 10.50,
    serviceChargeTotal: 4215.65,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/prime-residency-3-320.avif'],
    assets: [],
    netRoiMin: null,
    netRoiMax: null,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 4 ── JVT / Al Jawhara — Unit 1107 ────────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1107',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1107',
    floor: 11,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 457.25,
    apartmentSize: 457.25,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6093.52,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1107.avif'],
    assets: [],
    netRoiMin: 8.42,
    netRoiMax: 8.42,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 5 ── JVT / Al Jawhara — Unit 1307 ────────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1307',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1307',
    floor: 13,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 460.37,
    apartmentSize: 460.37,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6103.27,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1307.avif'],
    assets: [],
    netRoiMin: 8.64,
    netRoiMax: 8.64,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 6 ── JVT / Al Jawhara — Unit 2010 ────────────────────────────────────
  {
    title: 'Al Jawhara - Unit 2010',
    description: 'Furnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '2010',
    floor: 20,
    condition: 'Furnished & balcony',
    unitTotalSize: 436.48,
    apartmentSize: 436.48,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 5749.17,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-2010.avif'],
    assets: [],
    netRoiMin: 8.72,
    netRoiMax: 8.72,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 7 ── JVT / Al Jawhara — Unit 1608 ────────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1608',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1608',
    floor: 16,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 467.05,
    apartmentSize: 467.05,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6242.62,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1608.avif'],
    assets: [],
    netRoiMin: 5.19,
    netRoiMax: 5.19,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 8 ── JVT / Al Jawhara — Unit 1207 ────────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1207',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1207',
    floor: 12,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 460.59,
    apartmentSize: 460.59,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6106.62,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1207.avif'],
    assets: [],
    netRoiMin: 5.87,
    netRoiMax: 5.87,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 9 ── JVT / Al Jawhara — Unit 1405 ────────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1405',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1405',
    floor: 14,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 466.83,
    apartmentSize: 466.83,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6241.10,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1405.avif'],
    assets: [],
    netRoiMin: 8.39,
    netRoiMax: 8.39,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 10 ── JVT / Al Jawhara — Unit 1205 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1205',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1205',
    floor: 12,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 466.29,
    apartmentSize: 466.29,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6239.43,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1205.avif'],
    assets: [],
    netRoiMin: 8.39,
    netRoiMax: 8.39,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 11 ── JVT / Al Jawhara — Unit 907 ────────────────────────────────────
  {
    title: 'Al Jawhara - Unit 907',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '907',
    floor: 9,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 457.03,
    apartmentSize: 457.03,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6090.17,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-907.avif'],
    assets: [],
    netRoiMin: 8.42,
    netRoiMax: 8.42,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 12 ── JVT / Al Jawhara — Unit 1408 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1408',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1408',
    floor: 14,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 467.05,
    apartmentSize: 467.05,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6242.62,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1408.avif'],
    assets: [],
    netRoiMin: 3.13,
    netRoiMax: 3.13,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 13 ── JVT / Al Jawhara — Unit 1308 (VACANT) ──────────────────────────
  {
    title: 'Al Jawhara - Unit 1308',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1308',
    floor: 13,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 467.69,
    apartmentSize: 467.69,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6245.98,
    status: 'Vacant',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1308.avif'],
    assets: [],
    netRoiMin: null,
    netRoiMax: null,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: true,
  },
  // ── 14 ── JVT / Al Jawhara — Unit 1108 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1108',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1108',
    floor: 11,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 467.05,
    apartmentSize: 467.05,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6242.62,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1108.avif'],
    assets: [],
    netRoiMin: 3.44,
    netRoiMax: 3.44,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 15 ── JVT / Al Jawhara — Unit 1110 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1110',
    description: 'Furnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1110',
    floor: 11,
    condition: 'Furnished & balcony',
    unitTotalSize: 448.10,
    apartmentSize: 448.10,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 5785.27,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1110.avif'],
    assets: [],
    netRoiMin: 8.71,
    netRoiMax: 8.71,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 16 ── JVT / Al Jawhara — Unit 1208 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1208',
    description: 'Furnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1208',
    floor: 12,
    condition: 'Furnished & balcony',
    unitTotalSize: 469.74,
    apartmentSize: 469.74,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6252.52,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1208.avif'],
    assets: [],
    netRoiMin: 8.61,
    netRoiMax: 8.61,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 17 ── JVT / Al Jawhara — Unit 1007 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1007',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1007',
    floor: 10,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 460.37,
    apartmentSize: 460.37,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6103.27,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1007.avif'],
    assets: [],
    netRoiMin: 8.42,
    netRoiMax: 8.42,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 18 ── JVT / Al Jawhara — Unit 1508 (VACANT) ──────────────────────────
  {
    title: 'Al Jawhara - Unit 1508',
    description: 'Furnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1508',
    floor: 15,
    condition: 'Furnished & balcony',
    unitTotalSize: 469.74,
    apartmentSize: 469.74,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6252.52,
    status: 'Vacant',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1508.avif'],
    assets: [],
    netRoiMin: null,
    netRoiMax: null,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: true,
  },
  // ── 19 ── JVT / Al Jawhara — Unit 1310 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1310',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1310',
    floor: 13,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 444.66,
    apartmentSize: 444.66,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 5772.17,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1310.avif'],
    assets: [],
    netRoiMin: 2.42,
    netRoiMax: 2.42,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 20 ── JVT / Al Jawhara — Unit 1305 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1305',
    description: 'Semi-furnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1305',
    floor: 13,
    condition: 'Semi furnished & balcony',
    unitTotalSize: 466.29,
    apartmentSize: 466.29,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6239.43,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1305.avif'],
    assets: [],
    netRoiMin: 8.61,
    netRoiMax: 8.61,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 21 ── JVT / Al Jawhara — Unit 1105 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1105',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1105',
    floor: 11,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 466.83,
    apartmentSize: 466.83,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6241.10,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1105.avif'],
    assets: [],
    netRoiMin: 3.36,
    netRoiMax: 3.36,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 22 ── JVT / Al Jawhara — Unit 1210 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1210',
    description: 'Unfurnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1210',
    floor: 12,
    condition: 'Unfurnished & balcony',
    unitTotalSize: 444.33,
    apartmentSize: 444.33,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 5772.17,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1210.avif'],
    assets: [],
    netRoiMin: 8.72,
    netRoiMax: 8.72,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 23 ── JVT / Al Jawhara — Unit 1505 ───────────────────────────────────
  {
    title: 'Al Jawhara - Unit 1505',
    description: 'Furnished apartment with balcony in Al Jawhara, Jumeirah Village Triangle.',
    area: 'Jumeirah Village Triangle (JVT)',
    buildingName: 'Al Jawhara',
    contractValue: 450000,
    unitNo: '1505',
    floor: 15,
    condition: 'Furnished & balcony',
    unitTotalSize: 469.52,
    apartmentSize: 469.52,
    serviceChargePerSqft: 15.23,
    serviceChargeTotal: 6250.85,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/al-jawhara-1505.avif'],
    assets: [],
    netRoiMin: 8.61,
    netRoiMax: 8.61,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
  // ── 24 ── JLT/DMCC / Gold Tower — Unit 5A (B3-05-01) ────────────────────
  {
    title: 'Gold Tower - Unit 5A (B3-05-01)',
    description: 'Furnished commercial unit in Gold Tower, JLT/DMCC Freezone. High-rise tower with covered parking, restaurants and 24-hour security.',
    area: 'Jumeirah Lake Towers (JLT)',
    buildingName: 'Gold Tower',
    contractValue: 4100000,
    unitNo: 'B3-05-01',
    floor: 5,
    condition: 'Furnished',
    unitTotalSize: 1120.95,
    apartmentSize: 1120.95,
    serviceChargePerSqft: 19.17,
    serviceChargeTotal: 21488.61,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/gold-tower-b3-05-01.avif'],
    assets: [],
    netRoiMin: 18.22,
    netRoiMax: 18.22,
    isTaxFreeZone: true,
    keyBenefits: ['100% Foreign Ownership', 'Tax-Free Zone', 'Full Capital Repatriation'],
    freezoneAuthority: 'DMCC Freezone',
    isVacant: false,
  },
  // ── 25 ── JLT/DMCC / Mazaya — Unit 2905 ──────────────────────────────────
  {
    title: 'Mazaya - Unit 2905',
    description: 'Furnished commercial unit on the 29th floor of Mazaya Business Avenue, JLT/DMCC Freezone.',
    area: 'Jumeirah Lake Towers (JLT)',
    buildingName: 'Mazaya',
    contractValue: 3250000,
    unitNo: '2905',
    floor: 29,
    condition: 'Furnished',
    unitTotalSize: 1689.18,
    apartmentSize: 1689.18,
    serviceChargePerSqft: 13.08,
    serviceChargeTotal: 22094.47,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/mazaya-2905.avif'],
    assets: [],
    netRoiMin: 30.94,
    netRoiMax: 30.94,
    isTaxFreeZone: true,
    keyBenefits: ['100% Foreign Ownership', 'Tax-Free Zone', 'Full Capital Repatriation'],
    freezoneAuthority: 'DMCC Freezone',
    isVacant: false,
  },
  // ── 26 ── JLT/DMCC / Fortune Tower — Units 2005/2006 ─────────────────────
  {
    title: 'Fortune Tower - Units 2005/2006',
    description: 'Large furnished commercial unit spanning units 2005 & 2006 in Fortune Tower, JLT/DMCC Freezone.',
    area: 'Jumeirah Lake Towers (JLT)',
    buildingName: 'Fortune Tower',
    contractValue: 6600000,
    unitNo: '2005/2006',
    floor: 20,
    condition: 'Furnished',
    unitTotalSize: 2620.00,
    apartmentSize: 2620.00,
    serviceChargePerSqft: 14.88,
    serviceChargeTotal: 38985.60,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: [
      '/uploads/fortune-tower.avif',
      '/uploads/fortune-tower-767_xl-28129-resize_gallery.avif',
    ],
    assets: [],
    netRoiMin: 47.28,
    netRoiMax: 47.28,
    isTaxFreeZone: true,
    keyBenefits: ['100% Foreign Ownership', 'Tax-Free Zone', 'Full Capital Repatriation'],
    freezoneAuthority: 'DMCC Freezone',
    isVacant: false,
  },
  // ── 27 ── JLT/DMCC / Silver Tower — Unit 11K ─────────────────────────────
  {
    title: 'Silver Tower - Unit 11K',
    description: 'Furnished commercial unit on the 11th floor of Silver Tower, JLT/DMCC Freezone.',
    area: 'Jumeirah Lake Towers (JLT)',
    buildingName: 'Silver Tower',
    contractValue: 4550000,
    unitNo: '11K',
    floor: 11,
    condition: 'Furnished',
    unitTotalSize: 1164.00,
    apartmentSize: 1164.00,
    serviceChargePerSqft: null,
    serviceChargeTotal: null,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/silver-tower-11k.avif'],
    assets: [],
    netRoiMin: 56.59,
    netRoiMax: 56.59,
    isTaxFreeZone: true,
    keyBenefits: ['100% Foreign Ownership', 'Tax-Free Zone', 'Full Capital Repatriation'],
    freezoneAuthority: 'DMCC Freezone',
    isVacant: false,
  },
  // ── 28 ── JLT/DMCC / Silver Tower — Unit 4K ──────────────────────────────
  {
    title: 'Silver Tower - Unit 4K',
    description: 'Furnished commercial unit on the 4th floor of Silver Tower, JLT/DMCC Freezone.',
    area: 'Jumeirah Lake Towers (JLT)',
    buildingName: 'Silver Tower',
    contractValue: 4450000,
    unitNo: '4K',
    floor: 4,
    condition: 'Furnished',
    unitTotalSize: 1164.00,
    apartmentSize: 1164.00,
    serviceChargePerSqft: null,
    serviceChargeTotal: null,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/silver-tower-4k.avif'],
    assets: [],
    netRoiMin: null,
    netRoiMax: null,
    isTaxFreeZone: true,
    keyBenefits: ['100% Foreign Ownership', 'Tax-Free Zone', 'Full Capital Repatriation'],
    freezoneAuthority: 'DMCC Freezone',
    isVacant: false,
  },
  // ── 29 ── Dubai Marina / Marina Plaza — Unit 3503 ─────────────────────────
  {
    title: 'Marina Plaza - Unit 3503',
    description: 'Furnished apartment on the 35th floor of Marina Plaza, Dubai Marina.',
    area: 'Dubai Marina',
    buildingName: 'Marina Plaza',
    contractValue: 16300000,
    unitNo: '3503',
    floor: 35,
    condition: 'Furnished',
    unitTotalSize: 3724.31,
    apartmentSize: 3724.31,
    serviceChargePerSqft: null,
    serviceChargeTotal: 89968.04,
    status: 'Rented',
    city: 'Dubai',
    country: 'UAE',
    images: ['/uploads/properties/images/marina-plaza-3503.avif'],
    assets: [],
    netRoiMin: null,
    netRoiMax: null,
    isTaxFreeZone: false,
    keyBenefits: [],
    isVacant: false,
  },
];

/**
 * Tenant Lease seed data
 * Source: Assets 15.12.2025.csv — lease details for rented properties
 *
 * Each entry is keyed by the property unitNo so reset-seed can look up the
 * property ID after creating properties. lease.payments[] are nested for
 * convenience — the seed script creates them as separate RentPayment rows.
 */
export const tenantLeases: Array<{
  unitNo: string;
  tenantName: string;
  tenantEmail?: string;
  tenantPhone?: string;
  leaseStart: string;
  leaseEnd?: string;
  monthlyRent: number;
  annualRent: number;
  paymentMethod?: string;
  depositAmount?: number;
  payments: Array<{ amount: number; paidDate: string; type: PaymentType; note?: string }>;
}> = [
  // ── 1 ── Marina Pinnacle 5105 — (VACANT but had prior service charge payments to previous tenant)
  {
    unitNo: '5105',
    tenantName: 'Previous Tenant (Left)',
    leaseStart: '2024-01-01',
    leaseEnd: '2024-12-31',
    monthlyRent: 15500,
    annualRent: 186000,
    isActive: false,
    payments: [
      { amount: 15500, paidDate: '2025-01-15', type: PaymentType.MONTHLY },
      { amount: 15500, paidDate: '2025-02-15', type: PaymentType.MONTHLY },
      { amount: 15500, paidDate: '2025-03-15', type: PaymentType.MONTHLY },
      { amount: 15500, paidDate: '2025-04-15', type: PaymentType.MONTHLY },
      { amount: 15500, paidDate: '2025-05-15', type: PaymentType.MONTHLY },
    ],
  } as any,
  // ── 3 ── Prime Residency 3 · 320
  {
    unitNo: '320',
    tenantName: 'YSLAM ATAYEV',
    tenantEmail: 'jamescarter78.ia@gmail.com',
    leaseStart: '2025-05-07',
    leaseEnd: '2026-05-06',
    monthlyRent: 15000,
    annualRent: 60000,
    paymentMethod: 'Cheque',
    payments: [
      { amount: 15000, paidDate: '2025-05-15', type: PaymentType.ANNUAL, note: 'cheque/EIB personal' },
      { amount: 15000, paidDate: '2025-08-15', type: PaymentType.ANNUAL },
      { amount: 15000, paidDate: '2025-11-15', type: PaymentType.ANNUAL },
      { amount: 15000, paidDate: '2026-02-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 4 ── Al Jawhara · 1107
  {
    unitNo: '1107',
    tenantName: 'IMAD ALDEEN ABDULHALIM SHAMS',
    tenantEmail: 'imadaldeenshams@hotmail.com',
    tenantPhone: '971504373217',
    leaseStart: '2025-05-01',
    leaseEnd: '2026-04-30',
    monthlyRent: 11000,
    annualRent: 44000,
    paymentMethod: 'Cheque',
    depositAmount: 2200,
    payments: [
      { amount: 11000, paidDate: '2025-04-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 11000, paidDate: '2025-08-15', type: PaymentType.ANNUAL },
      { amount: 11000, paidDate: '2025-11-15', type: PaymentType.ANNUAL },
      { amount: 11000, paidDate: '2026-02-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 5 ── Al Jawhara · 1307
  {
    unitNo: '1307',
    tenantName: 'AHMAD ASHRAF AHMAD ALHAMMOURI',
    tenantEmail: 'ahmad.alhammouri92@gmail.com',
    tenantPhone: '971508553004',
    leaseStart: '2025-12-15',
    leaseEnd: '2026-12-14',
    monthlyRent: 15000,
    annualRent: 45000,
    paymentMethod: 'Cheque',
    depositAmount: 1600,
    payments: [
      { amount: 5950, paidDate: '2025-02-15', type: PaymentType.ANNUAL, note: 'FAB' },
      { amount: 5950, paidDate: '2025-04-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 5950, paidDate: '2025-06-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 5950, paidDate: '2025-08-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 5950, paidDate: '2025-10-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 6 ── Al Jawhara · 2010
  {
    unitNo: '2010',
    tenantName: 'MOHAMMAD TAWFIQ SADEQ JARRAR',
    tenantEmail: 'mjarrar92@gmail.com',
    tenantPhone: '971569419086',
    leaseStart: '2025-12-15',
    leaseEnd: '2026-12-15',
    monthlyRent: 45000,
    annualRent: 45000,
    paymentMethod: 'Cheque',
    depositAmount: 4000,
    payments: [
      { amount: 10000, paidDate: '2025-03-15', type: PaymentType.ANNUAL, note: 'CASH' },
      { amount: 10000, paidDate: '2025-06-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 10000, paidDate: '2025-09-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 7 ── Al Jawhara · 1608
  {
    unitNo: '1608',
    tenantName: 'MEHMET TATLI',
    tenantEmail: 'tatli.ethio@gmail.com',
    tenantPhone: '971564840264',
    leaseStart: '2025-02-18',
    leaseEnd: '2025-12-31',
    monthlyRent: 2961,
    annualRent: 34650,
    paymentMethod: 'Cheque',
    depositAmount: 1050,
    payments: [
      { amount: 29610, paidDate: '2025-02-15', type: PaymentType.ANNUAL, note: 'EIB — full contract value' },
    ],
  },
  // ── 8 ── Al Jawhara · 1207
  {
    unitNo: '1207',
    tenantName: 'YOUSRA ALI',
    tenantEmail: 'yfmohdali@hotmail.com',
    tenantPhone: '971555892600',
    leaseStart: '2025-03-10',
    leaseEnd: '2025-12-31',
    monthlyRent: 6500,
    annualRent: 40000,
    paymentMethod: 'Cheque',
    depositAmount: 2000,
    payments: [
      { amount: 6500, paidDate: '2025-03-15', type: PaymentType.MONTHLY, note: 'FAB' },
      { amount: 6500, paidDate: '2025-05-15', type: PaymentType.MONTHLY, note: 'Cheque/FAB' },
      { amount: 6500, paidDate: '2025-07-15', type: PaymentType.MONTHLY, note: 'cheque' },
      { amount: 6500, paidDate: '2025-09-15', type: PaymentType.MONTHLY },
      { amount: 6500, paidDate: '2025-11-15', type: PaymentType.MONTHLY },
    ],
  },
  // ── 9 ── Al Jawhara · 1405
  {
    unitNo: '1405',
    tenantName: 'SAM JR BASAS SANTOS',
    tenantEmail: 'samsantosjr3@gmail.com',
    tenantPhone: '971558495652',
    leaseStart: '2025-04-20',
    leaseEnd: '2026-04-19',
    monthlyRent: 11000,
    annualRent: 44000,
    paymentMethod: 'Cheque',
    depositAmount: 2200,
    payments: [
      { amount: 11000, paidDate: '2025-04-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 11000, paidDate: '2025-07-15', type: PaymentType.ANNUAL, note: 'cheque' },
      { amount: 11000, paidDate: '2025-10-15', type: PaymentType.ANNUAL },
      { amount: 11000, paidDate: '2026-01-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 10 ── Al Jawhara · 1205
  {
    unitNo: '1205',
    tenantName: 'ROHAN SUBHASH NAIR',
    tenantEmail: 'Rohanair00007@gmail.com',
    tenantPhone: '971507843856',
    leaseStart: '2025-05-25',
    leaseEnd: '2026-05-24',
    monthlyRent: 11000,
    annualRent: 44000,
    paymentMethod: 'Cheque',
    depositAmount: 2200,
    payments: [
      { amount: 10165, paidDate: '2025-08-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 11 ── Al Jawhara · 907
  {
    unitNo: '907',
    tenantName: 'ANURAG AGARWAL',
    tenantEmail: 'agarwalanurag20@yahoo.com',
    tenantPhone: '971585150327',
    leaseStart: '2025-04-24',
    leaseEnd: '2026-04-23',
    monthlyRent: 11000,
    annualRent: 44000,
    paymentMethod: 'Cheque',
    depositAmount: 2200,
    payments: [
      { amount: 7930, paidDate: '2025-04-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
    ],
  },
  // ── 12 ── Al Jawhara · 1408
  {
    unitNo: '1408',
    tenantName: 'MOHAMED ADEL AMIN YOUSSEF ABOSHANAB',
    tenantEmail: 'mohamed.adel.abushanab@gmail.com',
    tenantPhone: '971556323542',
    leaseStart: '2025-04-27',
    leaseEnd: '2025-12-31',
    monthlyRent: 10165,
    annualRent: 30000,
    paymentMethod: 'Cheque',
    depositAmount: 1050,
    payments: [
      { amount: 10165, paidDate: '2025-08-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 14 ── Al Jawhara · 1108
  {
    unitNo: '1108',
    tenantName: 'MOHAMMAD ABDEL HALIM ALALOUL',
    tenantEmail: 'mohammad.a.alaloul@gmail.com',
    tenantPhone: '971523445570',
    leaseStart: '2025-05-10',
    leaseEnd: '2025-12-31',
    monthlyRent: 7242,
    annualRent: 33600,
    paymentMethod: 'Cheque',
    depositAmount: 1600,
    payments: [
      { amount: 8400, paidDate: '2025-02-15', type: PaymentType.ANNUAL, note: 'FAB' },
      { amount: 8400, paidDate: '2025-05-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 8400, paidDate: '2025-08-15', type: PaymentType.ANNUAL },
      { amount: 4925, paidDate: '2025-11-15', type: PaymentType.ANNUAL, note: 'partial final payment' },
    ],
  },
  // ── 15 ── Al Jawhara · 1110 (no payments recorded yet — lease starts Nov 2025)
  {
    unitNo: '1110',
    tenantName: 'TENANT 1110',
    leaseStart: '2025-11-26',
    leaseEnd: '2026-11-25',
    monthlyRent: 3750,
    annualRent: 45000,
    paymentMethod: 'Cheque',
    payments: [],
  },
  // ── 16 ── Al Jawhara · 1208
  {
    unitNo: '1208',
    tenantName: 'ORAZDURDY MAMIYEV',
    tenantEmail: 'orazvasov@gmail.com',
    tenantPhone: '971505841730',
    leaseStart: '2025-05-07',
    leaseEnd: '2026-05-06',
    monthlyRent: 11250,
    annualRent: 45000,
    paymentMethod: 'Cheque',
    depositAmount: 2250,
    payments: [
      { amount: 11250, paidDate: '2025-05-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 11250, paidDate: '2025-08-15', type: PaymentType.ANNUAL },
      { amount: 11250, paidDate: '2025-11-15', type: PaymentType.ANNUAL },
      { amount: 11250, paidDate: '2026-02-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 17 ── Al Jawhara · 1007
  {
    unitNo: '1007',
    tenantName: 'RONNY ANDRADE DA SILVA',
    tenantEmail: 'ronnydasilva@outlook.com',
    tenantPhone: '971585772172',
    leaseStart: '2025-06-05',
    leaseEnd: '2026-06-04',
    monthlyRent: 11000,
    annualRent: 44000,
    paymentMethod: 'Cheque',
    depositAmount: 2000,
    payments: [
      { amount: 10000, paidDate: '2025-03-15', type: PaymentType.ANNUAL, note: 'EIB' },
    ],
  },
  // ── 18 ── Al Jawhara · 1508 — (VACANT in CSV but had previous tenant payments)
  {
    unitNo: '1508',
    tenantName: 'Previous Tenant 1508',
    leaseStart: '2024-07-01',
    leaseEnd: '2025-05-31',
    monthlyRent: 3333,
    annualRent: 40000,
    isActive: false,
    paymentMethod: 'Cash',
    payments: [
      { amount: 3333, paidDate: '2025-01-15', type: PaymentType.MONTHLY, note: 'Cash' },
      { amount: 3333, paidDate: '2025-02-15', type: PaymentType.MONTHLY, note: 'Cash' },
      { amount: 3333, paidDate: '2025-03-15', type: PaymentType.MONTHLY, note: 'Cash' },
      { amount: 3333, paidDate: '2025-04-15', type: PaymentType.MONTHLY, note: 'Cash' },
      { amount: 3350, paidDate: '2025-05-15', type: PaymentType.MONTHLY, note: 'Cash' },
    ],
  } as any,
  // ── 19 ── Al Jawhara · 1310
  {
    unitNo: '1310',
    tenantName: 'JASMIN TOLENTINO GO',
    tenantEmail: 'jastgo24@yahoo.com',
    tenantPhone: '971506401695',
    leaseStart: '2025-07-01',
    leaseEnd: '2025-12-31',
    monthlyRent: 8335,
    annualRent: 33340,
    paymentMethod: 'Cheque',
    depositAmount: 1650,
    payments: [
      { amount: 7930, paidDate: '2025-04-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 8334, paidDate: '2025-07-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 8334, paidDate: '2025-10-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 20 ── Al Jawhara · 1305
  {
    unitNo: '1305',
    tenantName: 'LAILA HASSAN DEEB',
    tenantEmail: 'deeblolo576@gmail.com',
    tenantPhone: '971585964772',
    leaseStart: '2025-09-16',
    leaseEnd: '2026-09-15',
    monthlyRent: 11250,
    annualRent: 45000,
    paymentMethod: 'Cheque',
    depositAmount: 2500,
    payments: [
      { amount: 7000, paidDate: '2025-03-15', type: PaymentType.ANNUAL, note: 'cheque/EIB' },
      { amount: 7000, paidDate: '2025-05-15', type: PaymentType.ANNUAL, note: 'Cheque/FAB' },
      { amount: 7000, paidDate: '2025-07-15', type: PaymentType.ANNUAL, note: 'cheque/FAB' },
      { amount: 13750, paidDate: '2025-09-15', type: PaymentType.ANNUAL },
      { amount: 11250, paidDate: '2025-12-15', type: PaymentType.ANNUAL },
      { amount: 11250, paidDate: '2026-03-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 21 ── Al Jawhara · 1105
  {
    unitNo: '1105',
    tenantName: 'MOHAMMAD TALAL AHMAD AL TAWEEL',
    tenantEmail: 'mohdtal_taweel@hotmail.com',
    tenantPhone: '971504451561',
    leaseStart: '2025-06-20',
    leaseEnd: '2025-12-31',
    monthlyRent: 10685,
    annualRent: 40000,
    paymentMethod: 'Cheque',
    depositAmount: 2000,
    payments: [
      { amount: 10000, paidDate: '2025-03-15', type: PaymentType.ANNUAL, note: 'EIB' },
      { amount: 10685, paidDate: '2025-06-15', type: PaymentType.ANNUAL, note: 'CASH' },
      { amount: 10685, paidDate: '2025-09-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 22 ── Al Jawhara · 1210
  {
    unitNo: '1210',
    tenantName: 'IBRAHIM AHMED ELSAYED ALI ELTORGOMAN',
    tenantEmail: 'ibrahimeltorgoman@gmail.com',
    tenantPhone: '971521401506',
    leaseStart: '2025-11-12',
    leaseEnd: '2026-11-11',
    monthlyRent: 15000,
    annualRent: 45000,
    paymentMethod: 'Cheque',
    depositAmount: 2250,
    payments: [
      { amount: 13330, paidDate: '2025-02-15', type: PaymentType.ANNUAL, note: 'EIB' },
      { amount: 13330, paidDate: '2025-06-15', type: PaymentType.ANNUAL, note: 'cheque bounced back' },
    ],
  },
  // ── 23 ── Al Jawhara · 1505
  {
    unitNo: '1505',
    tenantName: 'TENANT 1505',
    leaseStart: '2025-11-02',
    leaseEnd: '2026-11-01',
    monthlyRent: 4500,
    annualRent: 45000,
    paymentMethod: 'Cash',
    depositAmount: 4200,
    payments: [
      { amount: 7000, paidDate: '2025-03-15', type: PaymentType.ANNUAL, note: 'FAB' },
      { amount: 7000, paidDate: '2025-05-15', type: PaymentType.ANNUAL, note: 'Cheque/FAB' },
      { amount: 7000, paidDate: '2025-07-15', type: PaymentType.ANNUAL, note: 'Cheque/FAB' },
    ],
  },
  // ── 24 ── Gold Tower · B3-05-01 (2-year contract)
  {
    unitNo: 'B3-05-01',
    tenantName: 'AFFINITY SHIPPING DMCC',
    tenantEmail: 'john.widdrington@affinityship.com',
    tenantPhone: '971502750801',
    leaseStart: '2025-01-01',
    leaseEnd: '2026-12-31',
    monthlyRent: 32917,
    annualRent: 395000,
    paymentMethod: 'Bank transfer',
    depositAmount: 8500,
    payments: [
      { amount: 165000, paidDate: '2025-03-15', type: PaymentType.ANNUAL, note: 'EIB' },
      { amount: 197500, paidDate: '2025-07-15', type: PaymentType.ANNUAL, note: 'Bank transfer' },
      { amount: 197500, paidDate: '2026-01-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 25 ── Mazaya · 2905 (3-year contract, 1st year = 340k)
  {
    unitNo: '2905',
    tenantName: 'YOUMI INTERNATIONAL DMCC',
    leaseStart: '2025-02-01',
    leaseEnd: '2028-01-31',
    monthlyRent: 28333,
    annualRent: 340000,
    paymentMethod: 'Cheque',
    depositAmount: 34000,
    payments: [
      { amount: 107417.58, paidDate: '2025-05-15', type: PaymentType.ANNUAL, note: 'cheque/EIB' },
      { amount: 170000, paidDate: '2025-09-15', type: PaymentType.ANNUAL },
      { amount: 178500, paidDate: '2026-01-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 26 ── Fortune Tower · 2005/2006 (5-year contract, 1st year = 600k)
  {
    unitNo: '2005/2006',
    tenantName: 'POWER HORSE GLOBAL DMCC',
    tenantEmail: 'p-kayyur@power-horse.com',
    tenantPhone: '971504517657',
    leaseStart: '2025-05-01',
    leaseEnd: '2030-06-15',
    monthlyRent: 50000,
    annualRent: 600000,
    paymentMethod: 'Bank transfer',
    depositAmount: 70000,
    payments: [
      { amount: 200000, paidDate: '2025-08-15', type: PaymentType.ANNUAL, note: 'Bank transfer/FAB' },
      { amount: 200000, paidDate: '2025-11-15', type: PaymentType.ANNUAL },
      { amount: 200000, paidDate: '2026-02-15', type: PaymentType.ANNUAL },
    ],
  },
  // ── 27 ── Silver Tower · 11K (5-year contract, 1st year = 465,992)
  {
    unitNo: '11K',
    tenantName: 'LONDON DE LIMITED (DMCC BRANCH)',
    tenantEmail: 'philipspencere81@hotmail.co.uk',
    leaseStart: '2025-05-07',
    leaseEnd: '2030-05-06',
    monthlyRent: 38833,
    annualRent: 465992,
    paymentMethod: 'Cheque',
    depositAmount: 46599.20,
    payments: [
      { amount: 441734.88, paidDate: '2025-07-15', type: PaymentType.ANNUAL, note: 'bank transfer/FAB' },
    ],
  },
  // ── 28 ── Silver Tower · 4K (3-year contract, 1st year = 465k — no payments yet)
  {
    unitNo: '4K',
    tenantName: 'TENANT 4K',
    leaseStart: '2025-06-02',
    leaseEnd: '2028-06-30',
    monthlyRent: 38750,
    annualRent: 465000,
    paymentMethod: 'Cheque',
    depositAmount: 46500,
    payments: [],
  },
  // ── 29 ── Marina Plaza · 3503 (3-year contract, 1st year = 1.7M — no payments yet)
  {
    unitNo: '3503',
    tenantName: 'TENANT 3503',
    leaseStart: '2025-08-20',
    leaseEnd: '2028-08-19',
    monthlyRent: 141667,
    annualRent: 1700000,
    paymentMethod: 'Cheque',
    depositAmount: 170000,
    payments: [],
  },
];

/**
 * Events seed data
 */
export const events = [
  {
    title: 'Dubai Beach Picnic Afternoon',
    description:
      'Relaxing afternoon at Jumeirah Beach with food, games, and live acoustic music. Perfect for networking and family fun.',
    startsAt: new Date('2025-10-10T15:00:00Z'),
    endsAt: new Date('2025-10-10T20:00:00Z'),
    location: 'Jumeirah Beach, Dubai',
    totalMembers: 50,
    budget: 2500.0,
    image: '/uploads/4867.jpg',
    status: EventStatus.OPEN,
    isActive: true,
  },
  {
    title: 'Private Party at Dubai Marina',
    description:
      'An exclusive private party at a rooftop lounge in Dubai Marina. Invite-only event with premium catering and entertainment.',
    startsAt: new Date('2025-10-18T21:00:00Z'),
    endsAt: new Date('2025-10-19T02:00:00Z'),
    location: 'Dubai Marina, Rooftop Lounge',
    totalMembers: 120,
    budget: 15000.0,
    image: '/uploads/92743.jpg',
    status: EventStatus.OPEN,
    isActive: true,
  },
  {
    title: 'DJ Night at Downtown Dubai',
    description:
      'High-energy electronic music night featuring international DJs and stunning views of Burj Khalifa. Open to all music lovers.',
    startsAt: new Date('2025-11-01T22:00:00Z'),
    endsAt: new Date('2025-11-02T03:00:00Z'),
    location: 'Downtown Dubai, Burj Park',
    totalMembers: 300,
    budget: 25000.0,
    image: '/uploads/122068.jpg',
    status: EventStatus.OPEN,
    isActive: true,
  },
];
